jobs:
  - name: update-pipeline
    plan:
      - get: terraform-aws-ses-notification-service
        resource: terraform-aws-ses-notification-service-update-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
            dir: terraform-aws-ses-notification-service
          inputs:
            - name: terraform-aws-ses-notification-service
          outputs:
            - name: pipeline
      - set_pipeline: terraform-aws-ses-notification-service
        file: pipeline/aviator_pipeline.yml
